GET http://localhost:3001/api/blogs

###
DELETE http://localhost:3001/api/blogs/651d2b191fb3482996c1ce7b
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlJvYmVyIiwiaWQiOiI2NTBkOGQ5YjNkODdiYTRjNzJhYzc3NmIiLCJpYXQiOjE2OTY0MTIyNDYsImV4cCI6MTY5NjQxNTg0Nn0.59kzLypipZTr_nUDaMC7o7Cgm1BKm5kQg_EcrGr466Q

###
POST http://localhost:3001/api/blogs
Content-Type:application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlJvYmVyIiwiaWQiOiI2NTBkOGQ5YjNkODdiYTRjNzJhYzc3NmIiLCJpYXQiOjE2OTY0MTIyNDYsImV4cCI6MTY5NjQxNTg0Nn0.59kzLypipZTr_nUDaMC7o7Cgm1BKm5kQg_EcrGr466Q

    {
    "title": "Id removed from client",
    "author": "Robert C.Martin",
    "url": "http://blog.cleancoder.com/uncle-bob/2017/05/05/TestDefinitions.html",
    "likes": 9                
    }
###
PUT http://localhost:3001/api/blog/64c74e0041b899d56eda5a77
Content-Type:application/json


    {
        "title":"First class test",
        "author":"No author",
        "url": "http://fanthom/link",
        "likes": 1000
    }