GET http://localhost:3001/api/blog

###
DELETE http://localhost:3001/api/blog/64bd0f09ab4d0d9f0d55075b

###
POST http://localhost:3001/api/blogs
Content-Type:application/json


    {
    "title": "Why I do not miss React",
    "author": "Jack Franklin",
    "url": "https://www.jackfranklin.co.uk/blog/check-in-your-node-dependencies/",
    "likes": 8,
    "userId":"6504963a9a710a72a2810046"               
    
    }
###
PUT http://localhost:3001/api/blog/64c74e0041b899d56eda5a77
Content-Type:application/json


    {
        "title":"Non existing title",
        "author":"No author",
        "url": "http://fanthom/link",
        "likes": 1000
    }